### ISSUE TITLE
Grupos "separados" e falta de grupo ao criar no character

### ISSUE THREAD

**Issue by MarcosRenato266** [Sighmir/YARP#1]
Os níveis de grupos estão separados, o Super Admin não consegue usar comandos de grupos de nível inferior. E quando você cria um novo character ele não recebe o grupo de User para poder usar comandos básicos.

**Comment by felipe10fe** [comment]
se você coloca em classes/user.js
this._groups = groups || ['User'];
deve arrumar.

**Comment by Sighmir** [comment]
This issue was closed, its better to add a variable 'Default Group' in config/variables.js and then call user.giveGroup(yarp.variables['Default Group'].value) upon account creation in events/yarp/menu.js

**Comment by Sighmir** [comment]
Please next time try to use the [issues template](https://raw.githubusercontent.com/Sighmir/YARP/master/ISSUE_TEMPLATE.md). 
This way I will have all information necessary to understand your issue/request.
So please don't delete the issue template, it's supposed to be answered to help the whole community.
