### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by Jengas** [Sighmir/YARP#11]
**Is your feature request related to a problem? Please describe.**
There is Mongo database integrated to the YARP, but there is no MySQL support

**Describe the solution you'd like**
Abitily to use MySQL as database rather than Mongo

**Describe alternatives you've considered**
empty

**Additional context**
empty

**Comment by Sighmir** [comment]
The choice to use MongoDB wasn't by preference or arbitrary, it has a reason, MongoDB is much more flexible. MySQL is great for projects that will benefit from its pre-defined structure and set schemas, but YARP can't have set schemas as the objective of the project is to let you (the server owner) create any Javascript object, with any schema and save their states to the database without needing a table or a set schema existing for it. With MySQL you would have to create new table and schema for every new object.

Changing the database on YARP from MongoDB to MySQL would be like buying a plane, cutting off it's wings and calling it a boat.

What would be the reason for you to want this change exactly ?

**Comment by Sighmir** [comment]
You might want to read a few pages about MySQL and NoSQL and it's main differences and uses.

You have to use the right tool for the right job. 👍
