### ISSUE TITLE
Can´t create Character

### ISSUE THREAD

**Issue by SupperCraft5000** [Sighmir/YARP#13]
**Describe the bug**
When i create a Character then i become an error.

**To Reproduce**
yes i can repruduce it
**Steps to reproduce the behavior:**
2. Click on create Character
4. See error in console

**Expected behavior**
/

**Screenshots**
/

**Desktop (please complete the following information):**
 - Server OS: Windows Server 2016
 - Game Version: zz. latest
**Additional context**
The Console Error:

`(node:6356) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'characters' of undefined
(node:6356) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by Sighmir** [comment]
This problem might have been introduced by a recent update. The Proxy is kinda a work in progress right now. I will fix this as soon as I can.

**Comment by Sighmir** [comment]
The error was on line 23 of character.js
    yarp.client.showPlayerCharacters(player, character.user.characters);
should be:
    yarp.client.showPlayerCharacters(player, player.user.characters);
because character is not loaded yet for user during character creation.
