### ISSUE TITLE
nothing works

### ISSUE THREAD

**Issue by Ownness** [Sighmir/YARP#15]
There are a lot of marvers on the map, but nothing works, help...

**Comment by Sighmir** [comment]
Please leave a better description of your issue. This framework is a work in progress and it's intended for developers to use it or borrow parts of it to help them build their servers.

**Comment by Ownness** [comment]
There are a lot of icons on the map (work, ATMs, refueling), but when you arrive at the place, there are no collshapes. ATMs don't work, and everything else. maybe I did not install something ... did according to the instructions

**Comment by Sighmir** [comment]
Oh the blips are there to make important positions that you might use for your server, but they are not all implemented. I actually only had time to implement the stores and ammunations so far.. I hope I can come back to this project in the future but at the moment I haven't got much time.
I have been anxiously waiting for RAGE 0.4.

**Comment by Ownness** [comment]
will you still be engaged in the project?

**Comment by Sighmir** [comment]
When I have more time and RAGE.MP 0.4 is released.
