### ISSUE TITLE
Valores de character igual a zero geram erro de inicialização

### ISSUE THREAD

**Issue by MarcosRenato266** [Sighmir/YARP#2]
Valores como Wallet no construtor de character retornam erro.

**Comment by Sighmir** [comment]
This was fixed by moving the variables config to the requirements loader and changing the default values the the arguments instead of object construction. This also made the code more readable.

This probably have a few side effects.. but I will fix them as they show up :)

**Comment by Sighmir** [comment]
Please next time try to use the [issues template](https://raw.githubusercontent.com/Sighmir/YARP/master/ISSUE_TEMPLATE.md). 
This way I will have all information necessary to understand your issue/request.
So please don't delete the issue template, it's supposed to be answered to help the whole community.
