### ISSUE TITLE
Item [restoreHunger,restoreThirst] 

### ISSUE THREAD

**Issue by felipe10fe** [Sighmir/YARP#5]
Estou enviando um ...
- [x] bug report 

Qual é o comportamento atual?
Quando consome muita comida, seu hp fica o valor da comida.

Se o comportamento atual é um bug, por favor, forneça as etapas para corrigir o problema

```
mp.events.add('restoreHunger', (player, value) => {
  let character = yarp.characters[player.name];
  let hunger = character.hunger-value;
  let hp = player.health+value;
  if (hunger > 0) {
    character.hunger = hunger;
  } else {
    character.hunger = 0;
    if (hp < 100){
      player.health = hp;
    }else{
      player.health = 100;
    }
  }
});
```

Qual é o comportamento esperado?
Assim que a fome ficar 0, ele recupera o hp.

Qual é a motivação / caso de uso para mudar o comportamento?
bug ?

**Comment by Sighmir** [comment]
Sorry but thats not what this piece of code do.
I will comment what you are actually doing.
```
mp.events.add('restoreHunger', (player, value) => {
  let character = yarp.characters[player.name]; // Get character
  let hunger = character.hunger-value; // Subtract hunger
  let hp = player.health+value; // Adds value subtracted from hunger, to health
  if (hunger > 0) { // If hunger bigger than 0
    character.hunger = hunger; // His hunger will be equal the new subtracted hunger
  } else { // If his hunger is smaller than 0
    character.hunger = 0; // Character hunger equals 0
    if (hp < 100){ // If the new HP smaller than 100
      player.health = hp; // Character hp equals HP
    }else{ // Else if HP bigger than 100
      player.health = 100; // Player health equals 100
    }
  }
});
```
So as you can see not in any time you made the consumables lower the health if you eat with your stomach full. All you do here is lower the hunger the same value you increase the health when using a consumable.

**Comment by Sighmir** [comment]
I just noticed that this could be a feature request instead of a bug report, if this is a feature request I will get it done after the bank.

Please next time try to use the [issues template](https://raw.githubusercontent.com/Sighmir/YARP/master/ISSUE_TEMPLATE.md). 
This way I will have all information necessary to understand your issue/request.
So please don't delete the issue template, it's supposed to be answered to help me and others.

**Comment by felipe10fe** [comment]
malz é que o seu faz com que o hp fique o valor da fome.

**Comment by Sighmir** [comment]
Thanks now I understand, I will add this to the todo list and check on it later, it will probably come with the bank fix.

**Comment by Sighmir** [comment]
I just took a look at this function, and I believe its working as intended.
```
mp.events.add('restoreHunger', (player, value) => {
  let character = yarp.characters[player.name]; // Aquire user character
  let hunger = character.hunger-value[0]; // Subtracts value from character hunger
  if (hunger > 0) { // If the new hunger is positive
    character.hunger = hunger; // Character hunger equals new hunger
  } else { // Else if the new hunger is a negative number
    character.hunger = 0; // Set character hunger to 0, because it can't be negative
    player.health += hunger; // Add the negative value to health
    // ^ this damages the player for the same value he overate.
  }
});
```
