### ISSUE TITLE
Inventario 

### ISSUE THREAD

**Issue by felipe10fe** [Sighmir/YARP#8]
* **Estou enviando um ...**
  - [ ] relatório de erro 
  - [ ] feature request  

* **Qual é o comportamento atual?**
Quando compro algum item o inventario não carrega.

**Comment by Sighmir** [comment]
The inventory and item usage has been tested before last push, are you sure you updated your files correctly ?

**Comment by Sighmir** [comment]
Just tested this again, everything working as expected. Minor fixes needed on the display, as the value don't update until it's bigger than zero, but that is not in any way related to the inventory.
