### ISSUE TITLE
Inventario

### ISSUE THREAD

**Issue by felipe10fe** [Sighmir/YARP#9]
* **I'm submitting a ...**
  - [x] bug report 
  - [ ] feature request  

* **What is the current behavior?**

Inventario não mostra os itens. ( Clone da ultima versão do YARP )

* **Other information** 

gif
https://giphy.com/gifs/NQhq51auMfyuip3cVf

**Comment by Sighmir** [comment]
Like I said on issue #8 this has been tested and re-tested after the issue was created, I can't reproduce the problem, everything is working as expected.

**Comment by felipe10fe** [comment]
como eu resolvo então? já baixei tudo de novo é ainda fica sem os itens no inventario.
